// Package testrepo builds a complete, working participant repo from nothing, in a temp
// directory, so tests can drive the real tool handlers against a real registry with real signed
// records.
//
// It exists because the tests used to point at a hand-made local clone by absolute path. When
// those demo repos were reorganized the path went stale, every test touching a real registry
// quietly turned into a skip, and the suite kept reporting success while verifying nothing —
// exactly the failure mode the federation itself is built to prevent.
//
// Nothing here fakes or bypasses the cockpit's own checks. The repo it builds is a real git repo
// whose `origin` really is a github.com URL, so the anti-wrong-folder guard runs unmodified; only
// the remote's *push* URL points at a local bare repo, so commits and pushes complete offline
// without inventing a GitHub repository. Keys are generated by the real plankton/nekton binaries
// and every record a test writes is genuinely signed.
package testrepo

import (
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/deathbychoco/claude-science-cockpit/internal/config"
)

// The identity the built repo claims. Owner/Name only ever appear in the remote URL and the
// config; no such GitHub repo exists or is contacted.
const (
	Owner     = "cockpit-test"
	Name      = "participant-fixture"
	SessionID = "session-1"
)

// Repo is one built participant repo.
type Repo struct {
	Root   string // the working repo: git root, cockpit.config.json, registries, keys, bin
	Origin string // the bare repo that pushes actually land in
}

// New builds a participant repo from nothing and returns it. Every step a human operator would
// perform is performed here: git init, a remote, the registry/keys/templates/bin layout, a real
// signing identity from `plankton keygen`/`nekton keygen`, the two claim templates the default
// config allows, a cockpit.config.json, and an initial commit pushed to the remote.
func New(t *testing.T) *Repo {
	t.Helper()

	base := t.TempDir()
	r := &Repo{
		Root:   filepath.Join(base, "repo"),
		Origin: filepath.Join(base, "origin.git"),
	}

	git(t, base, "init", "--bare", "--quiet", "-b", "main", r.Origin)
	if err := os.MkdirAll(r.Root, 0o755); err != nil {
		t.Fatal(err)
	}
	git(t, r.Root, "init", "--quiet", "-b", "main")

	// The fetch URL is what the anti-wrong-folder guard reads (`git remote get-url origin`), so it
	// must be the real github.com form the config claims. The push URL is set separately to the
	// local bare repo, which `get-url` without --push does not report — so the guard sees exactly
	// what it would see in production while pushes stay offline. (An `insteadOf` rewrite would NOT
	// work here: that one does rewrite `get-url`, and the guard would then see a local path.)
	git(t, r.Root, "remote", "add", "origin", "git@github.com:"+Owner+"/"+Name+".git")
	git(t, r.Root, "remote", "set-url", "--push", "origin", r.Origin)

	for _, d := range []string{"registry/plankton", "registry/nekton", "registry/keys", "templates", "keys", "bin", "data"} {
		if err := os.MkdirAll(filepath.Join(r.Root, d), 0o755); err != nil {
			t.Fatal(err)
		}
	}

	plankton, nekton := resolveBinaries(t)
	copyFile(t, plankton, filepath.Join(r.Root, "bin", "plankton"))
	copyFile(t, nekton, filepath.Join(r.Root, "bin", "nekton"))

	// Real keypairs from the real binaries — the trust tiers below name the .pub these emit, so
	// verification resolves a tier from the actual verifying key, as in production.
	run(t, r.Root, filepath.Join(r.Root, "bin", "plankton"), "keygen", "keys/"+SessionID)
	run(t, r.Root, filepath.Join(r.Root, "bin", "nekton"), "keygen", "keys/"+SessionID+"-claims")

	// The two halves go to different places, and this is the layout, not a detail: the private
	// .key stays in /keys/, which .gitignore excludes, while the .pub is copied to registry/keys/
	// and IS committed — a peer cannot verify this participant's signatures without it.
	for _, base := range []string{SessionID, SessionID + "-claims"} {
		copyFile(t, filepath.Join(r.Root, "keys", base+".pub"), filepath.Join(r.Root, "registry", "keys", base+".pub"))
	}

	// The claim templates and the key hygiene come from uat/participant-skeleton, so this fixture
	// and the UAT scaffold participants from one definition rather than two that can drift.
	skeleton := filepath.Join(cockpitRoot(t), "uat", "participant-skeleton")
	copyFile(t, filepath.Join(skeleton, "gitignore"), filepath.Join(r.Root, ".gitignore"))
	for _, tmpl := range []string{"reproduces.json", "working-on.json"} {
		copyFile(t, filepath.Join(skeleton, "templates", tmpl), filepath.Join(r.Root, "templates", tmpl))
	}

	b, err := json.MarshalIndent(DefaultConfig(), "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(r.Root, "cockpit.config.json"), string(b)+"\n")

	git(t, r.Root, "add", "-A")
	git(t, r.Root, "-c", "user.name=fixture", "-c", "user.email=fixture@cockpit.local", "commit", "--quiet", "-m", "fixture: participant repo")
	git(t, r.Root, "push", "--quiet", "-u", "origin", "main")

	return r
}

// DefaultConfig is the cockpit.config.json the fixture writes: the same shape `cockpit init`
// scaffolds, with the trust tier filled in to name this repo's own generated pubkeys.
func DefaultConfig() config.Raw {
	return config.Raw{
		Repo: config.RepoRef{Owner: Owner, Name: Name},
		Paths: config.Paths{
			PlanktonDir:  "registry/plankton",
			NektonDir:    "registry/nekton",
			TemplatesDir: "templates",
			KeysDir:      "keys",
			BinDir:       "bin",
		},
		Identity: config.Identity{
			SessionID:   SessionID,
			PlanktonKey: "keys/" + SessionID + ".key",
			NektonKey:   "keys/" + SessionID + "-claims.key",
		},
		Verbs:  config.Verbs{Publish: true, Say: true, Ask: true},
		Claims: config.Claims{AllowedTemplates: []string{"reproduces", "working-on"}},
		Trust: config.Trust{Tiers: map[string][]string{
			"self": {"registry/keys/" + SessionID + ".pub", "registry/keys/" + SessionID + "-claims.pub"},
		}},
		Reproduction: config.Reproduction{RequiredLevel: "L0"},
	}
}

// Use points the cockpit at this repo for the duration of the test, via the same COCKPIT_REPO_DIR
// override a human operator configures for an MCP client that cannot set a working directory. It
// is used instead of chdir so tests never depend on — or disturb — the process's cwd.
func (r *Repo) Use(t *testing.T) {
	t.Helper()
	t.Setenv("COCKPIT_REPO_DIR", r.Root)
}

// Config loads the built repo's config through the real loader, guard included.
func (r *Repo) Config(t *testing.T) *config.Config {
	t.Helper()
	cfg, err := config.Load(context.Background(), r.Root)
	if err != nil {
		t.Fatalf("loading the fixture's own config failed: %v", err)
	}
	return cfg
}

// Write puts content at a repo-relative path, creating parent directories. Use it for the input
// and output files a publish is about.
func (r *Repo) Write(t *testing.T, relPath, content string) string {
	t.Helper()
	abs := filepath.Join(r.Root, relPath)
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, abs, content)
	return relPath
}

// HeadSHA is the working repo's current HEAD, for asserting that a handler actually committed.
func (r *Repo) HeadSHA(t *testing.T) string {
	t.Helper()
	return git(t, r.Root, "rev-parse", "HEAD")
}

// OriginSHA is the bare remote's current main, for asserting that a handler actually pushed.
func (r *Repo) OriginSHA(t *testing.T) string {
	t.Helper()
	return git(t, r.Origin, "rev-parse", "main")
}

// OriginContains reports whether the bare remote's main already contains sha. Publish commits
// twice — the data files first, then the registry — and pins its permalinks to the FIRST of the
// two, so the sha it reports is deliberately an ancestor of the remote tip, not equal to it.
func (r *Repo) OriginContains(t *testing.T, sha string) bool {
	t.Helper()
	cmd := exec.Command("git", "--git-dir", r.Origin, "merge-base", "--is-ancestor", sha, "main")
	cmd.Dir = filepath.Dir(r.Origin)
	return cmd.Run() == nil
}

// TrackedFiles lists every path git actually tracks in the working repo.
func (r *Repo) TrackedFiles(t *testing.T) []string {
	t.Helper()
	out := git(t, r.Root, "ls-files")
	if out == "" {
		return nil
	}
	return strings.Split(out, "\n")
}
