// Package testrepo builds a complete, working participant repo from nothing, in a temp
// directory, so tests can drive the real tool handlers against a real registry with real signed
// records.
//
// It exists because the tests used to point at a hand-made local clone by absolute path. When
// those demo repos were reorganized the path went stale, every test touching a real registry
// quietly turned into a skip, and the suite kept reporting success while verifying nothing —
// exactly the failure mode the federation itself is built to prevent.
//
// Nothing here fakes or bypasses the cockpit's own checks. The repo it builds is a real git repo
// whose `origin` really is a github.com URL, so the anti-wrong-folder guard runs unmodified; only
// the remote's *push* URL points at a local bare repo, so commits and pushes complete offline
// without inventing a GitHub repository. Keys are generated by the real plankton/nekton binaries
// and every record a test writes is genuinely signed.
package testrepo

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/deathbychoco/claude-science-cockpit/internal/config"
)

// The identity the built repo claims. Owner/Name only ever appear in the remote URL and the
// config; no such GitHub repo exists or is contacted.
const (
	Owner     = "cockpit-test"
	Name      = "participant-fixture"
	SessionID = "session-1"
)

// Repo is one built participant repo.
type Repo struct {
	Root   string // the working repo: git root, cockpit.config.json, registries, keys, bin
	Origin string // the bare repo that pushes actually land in; unused in local mode
	Local  bool   // built with no git repository at all
}

// New builds a participant repo from nothing and returns it. Every step a human operator would
// perform is performed here: git init, a remote, the registry/keys/templates/bin layout, a real
// signing identity from `plankton keygen`/`nekton keygen`, the two claim templates the default
// config allows, a cockpit.config.json, and an initial commit pushed to the remote.
func New(t *testing.T) *Repo {
	t.Helper()
	return buildRepo(t, false)
}

// NewLocal builds the same participant directory with no git repository at all — repo.mode
// "local", where the guard checks that the config is where it declares itself to be rather than
// what a remote says. See ADR-004.
func NewLocal(t *testing.T) *Repo {
	t.Helper()
	return buildRepo(t, true)
}

func buildRepo(t *testing.T, local bool) *Repo {
	t.Helper()

	base := t.TempDir()
	r := &Repo{
		Root:   filepath.Join(base, "repo"),
		Origin: filepath.Join(base, "origin.git"),
		Local:  local,
	}

	if !local {
		git(t, base, "init", "--bare", "--quiet", "-b", "main", r.Origin)
	}
	if err := os.MkdirAll(r.Root, 0o755); err != nil {
		t.Fatal(err)
	}
	if !local {
		git(t, r.Root, "init", "--quiet", "-b", "main")
	}

	// The fetch URL is what the anti-wrong-folder guard reads (`git remote get-url origin`), so it
	// must be the real github.com form the config claims. The push URL is set separately to the
	// local bare repo, which `get-url` without --push does not report — so the guard sees exactly
	// what it would see in production while pushes stay offline. (An `insteadOf` rewrite would NOT
	// work here: that one does rewrite `get-url`, and the guard would then see a local path.)
	if !local {
		git(t, r.Root, "remote", "add", "origin", "git@github.com:"+Owner+"/"+Name+".git")
		git(t, r.Root, "remote", "set-url", "--push", "origin", r.Origin)
	}

	for _, d := range []string{"registry/plankton", "registry/nekton", "registry/keys", "templates", "keys", "bin", "data"} {
		if err := os.MkdirAll(filepath.Join(r.Root, d), 0o755); err != nil {
			t.Fatal(err)
		}
	}

	plankton, nekton, kton := resolveBinaries(t)
	copyFile(t, plankton, filepath.Join(r.Root, "bin", "plankton"))
	copyFile(t, nekton, filepath.Join(r.Root, "bin", "nekton"))
	copyFile(t, kton, filepath.Join(r.Root, "bin", "kton"))

	// Real keypairs from the real binaries — the trust tiers below name the .pub these emit, so
	// verification resolves a tier from the actual verifying key, as in production.
	run(t, r.Root, filepath.Join(r.Root, "bin", "plankton"), "keygen", "keys/"+SessionID)
	run(t, r.Root, filepath.Join(r.Root, "bin", "nekton"), "keygen", "keys/"+SessionID+"-claims")

	// The two halves go to different places, and this is the layout, not a detail: the private
	// .key stays in /keys/, which .gitignore excludes, while the .pub is copied to registry/keys/
	// and IS committed — a peer cannot verify this participant's signatures without it.
	for _, base := range []string{SessionID, SessionID + "-claims"} {
		copyFile(t, filepath.Join(r.Root, "keys", base+".pub"), filepath.Join(r.Root, "registry", "keys", base+".pub"))
	}

	// The claim templates and the key hygiene come from uat/participant-skeleton, so this fixture
	// and the UAT scaffold participants from one definition rather than two that can drift.
	skeleton := filepath.Join(cockpitRoot(t), "uat", "participant-skeleton")
	copyFile(t, filepath.Join(skeleton, "gitignore"), filepath.Join(r.Root, ".gitignore"))
	for _, tmpl := range []string{"reproduces.json", "working-on.json"} {
		copyFile(t, filepath.Join(skeleton, "templates", tmpl), filepath.Join(r.Root, "templates", tmpl))
	}

	raw := DefaultConfig()
	if local {
		raw.Repo = config.RepoRef{Mode: config.ModeLocal, Root: r.Root}
	}
	r.WriteConfig(t, raw)

	if !local {
		git(t, r.Root, "add", "-A")
		git(t, r.Root, "-c", "user.name=fixture", "-c", "user.email=fixture@cockpit.local", "commit", "--quiet", "-m", "fixture: participant repo")
		git(t, r.Root, "push", "--quiet", "-u", "origin", "main")
	}

	return r
}

// DefaultConfig is the cockpit.config.json the fixture writes: the same shape `cockpit init`
// scaffolds, with the trust tier filled in to name this repo's own generated pubkeys.
func DefaultConfig() config.Raw {
	return config.Raw{
		Repo: config.RepoRef{Owner: Owner, Name: Name},
		Paths: config.Paths{
			PlanktonDir:  "registry/plankton",
			NektonDir:    "registry/nekton",
			TemplatesDir: "templates",
			KeysDir:      "keys",
			BinDir:       "bin",
		},
		Identity: config.Identity{
			SessionID:   SessionID,
			PlanktonKey: "keys/" + SessionID + ".key",
			NektonKey:   "keys/" + SessionID + "-claims.key",
		},
		Verbs:  config.Verbs{Publish: true, Say: true, Ask: true},
		Claims: config.Claims{AllowedTemplates: []string{"reproduces", "working-on"}},
		Trust: config.Trust{Tiers: map[string][]string{
			"self": {"registry/keys/" + SessionID + ".pub", "registry/keys/" + SessionID + "-claims.pub"},
		}},
		Reproduction: config.Reproduction{RequiredLevel: "L0"},
	}
}

// Use points the cockpit at this repo for the duration of the test, via the same COCKPIT_REPO_DIR
// override a human operator configures for an MCP client that cannot set a working directory. It
// is used instead of chdir so tests never depend on — or disturb — the process's cwd.
func (r *Repo) Use(t *testing.T) {
	t.Helper()
	t.Setenv("COCKPIT_REPO_DIR", r.Root)
}

// Config loads the built repo's config through the real loader, guard included.
func (r *Repo) Config(t *testing.T) *config.Config {
	t.Helper()
	cfg, err := config.Load(context.Background(), r.Root)
	if err != nil {
		t.Fatalf("loading the fixture's own config failed: %v", err)
	}
	return cfg
}

// Write puts content at a repo-relative path, creating parent directories. Use it for the input
// and output files a publish is about.
func (r *Repo) Write(t *testing.T, relPath, content string) string {
	t.Helper()
	abs := filepath.Join(r.Root, relPath)
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, abs, content)
	return relPath
}

// HeadSHA is the working repo's current HEAD, for asserting that a handler actually committed.
func (r *Repo) HeadSHA(t *testing.T) string {
	t.Helper()
	return git(t, r.Root, "rev-parse", "HEAD")
}

// OriginSHA is the bare remote's current main, for asserting that a handler actually pushed.
func (r *Repo) OriginSHA(t *testing.T) string {
	t.Helper()
	return git(t, r.Origin, "rev-parse", "main")
}

// OriginContains reports whether the bare remote's main already contains sha. Publish commits
// twice — the data files first, then the registry — and pins its permalinks to the FIRST of the
// two, so the sha it reports is deliberately an ancestor of the remote tip, not equal to it.
func (r *Repo) OriginContains(t *testing.T, sha string) bool {
	t.Helper()
	cmd := exec.Command("git", "--git-dir", r.Origin, "merge-base", "--is-ancestor", sha, "main")
	cmd.Dir = filepath.Dir(r.Origin)
	return cmd.Run() == nil
}

// TrackedFiles lists every path git actually tracks in the working repo.
func (r *Repo) TrackedFiles(t *testing.T) []string {
	t.Helper()
	out := git(t, r.Root, "ls-files")
	if out == "" {
		return nil
	}
	return strings.Split(out, "\n")
}

// WriteConfig replaces the repo's cockpit.config.json, for tests that need a configuration
// different from the default.
func (r *Repo) WriteConfig(t *testing.T, raw config.Raw) {
	t.Helper()
	b, err := json.MarshalIndent(raw, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(r.Root, "cockpit.config.json"), string(b)+"\n")
}

// Bool is a helper for the config's optional booleans, whose zero value has to stay
// distinguishable from an explicit false.
func Bool(b bool) *bool { return &b }

// StubAnchor replaces bin/kton with a wrapper that answers `kton anchor` from a canned Rekor entry
// and passes every other subcommand — `serve` above all — to the real binary.
//
// It stubs the one thing that cannot honestly be exercised offline. Anchoring writes to a public,
// permanent transparency log; the kernel gates its own live test behind a `live` build tag for that
// reason, and a suite that anchored on every run would leave a trail of test entries nobody can
// withdraw. What this DOES cover is everything on this side of the network: that the envelope is
// found by id, written where kton expects it, that the printed entry is read correctly, and that
// the proof is attached to the record and committed with it. What it does NOT cover is that Rekor
// behaves as expected — that is the live test's job, and this comment is here so nobody mistakes a
// green run for one.
func (r *Repo) StubAnchor(t *testing.T, logIndex int64, uuid string) {
	t.Helper()
	real := filepath.Join(r.Root, "bin", "kton.real")
	if err := os.Rename(filepath.Join(r.Root, "bin", "kton"), real); err != nil {
		t.Fatal(err)
	}
	script := fmt.Sprintf(`#!/bin/sh
if [ "$1" = anchor ]; then
  echo "anchored in Rekor: logIndex=%d  uuid=%s"
  echo "  inclusion proof + SET verified against Rekor's public key (independent witness)"
  printf '{\n  "logIndex": %d,\n  "uuid": "%s",\n  "integratedTime": 1788000000\n}\n'
  exit 0
fi
exec %q "$@"
`, logIndex, uuid, logIndex, uuid, real)
	writeFile(t, filepath.Join(r.Root, "bin", "kton"), script)
	if err := os.Chmod(filepath.Join(r.Root, "bin", "kton"), 0o755); err != nil {
		t.Fatal(err)
	}
}

// SeedScope opens a nekton scope in this repo's registry and returns its id, the way an operator
// would before pointing a config at it: `nekton seed` is not one of the three verbs, so a scope is
// something that exists before the session ever runs.
//
// The seed is signed with the repo's own claim key and ingested directly, so the scope is real —
// tests chain against the substrate's own head, never against a hand-written id.
func (r *Repo) SeedScope(t *testing.T, name string) string {
	t.Helper()
	out := runNekton(t, r, "seed", name, "--sign", "keys/"+SessionID+"-claims.key", "--add", "--print-id")
	id := strings.TrimSpace(out)
	if !strings.HasPrefix(id, "sha256:") || len(id) != 71 {
		t.Fatalf("nekton seed --print-id did not return a scope id, got %q", out)
	}
	return id
}

// ScopeHead reports the current tip and chain length, so a test can assert that a claim actually
// advanced the chain rather than merely being accepted.
func (r *Repo) ScopeHead(t *testing.T, scopeID string) (tip string, chainLength int, branched bool) {
	t.Helper()
	out := runNekton(t, r, "head", scopeID, "--json")
	var h struct {
		Heads       []string `json:"heads"`
		ChainLength int      `json:"chainLength"`
		Branched    bool     `json:"branched"`
	}
	if err := json.Unmarshal([]byte(out), &h); err != nil || len(h.Heads) == 0 {
		t.Fatalf("could not read the head of %s: %v\n%s", scopeID, err, out)
	}
	return h.Heads[0], h.ChainLength, h.Branched
}

// runNekton invokes the fixture's own nekton with this repo's registry pinned exactly as the
// cockpit pins it. Without NEKTON_DIR it would read its bare ./nekton-data default, which is a
// different, empty registry that answers with no scope and no error.
func runNekton(t *testing.T, r *Repo, args ...string) string {
	t.Helper()
	cmd := exec.Command(filepath.Join(r.Root, "bin", "nekton"), args...)
	cmd.Dir = r.Root
	cmd.Env = append(os.Environ(),
		"NEKTON_DIR="+filepath.Join(r.Root, "registry", "nekton"),
		"NEKTON_TEMPLATES="+filepath.Join(r.Root, "templates"))
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("nekton %s: %v\n%s", strings.Join(args, " "), err, out)
	}
	return strings.TrimSpace(string(out))
}

// ChainClaimDirectly writes a scoped claim straight through nekton, bypassing the cockpit, so a
// test can produce a state the cockpit itself refuses to produce — a branched scope.
//
// Going around the tool under test is the point here rather than a shortcut: a fork is exactly what
// arrives when a peer's branch is mirrored in, and no amount of correct behaviour by this cockpit
// prevents one turning up. The refusal has to be tested against a fork it did not cause.
func (r *Repo) ChainClaimDirectly(t *testing.T, subject, scope, prev, step string) string {
	t.Helper()
	id := runNekton(t, r, "annotate", subject,
		"--template", "working-on",
		"--set", "step="+step,
		"--set", "by-session="+SessionID,
		"--scope", scope, "--prev", prev,
		"--sign", "keys/"+SessionID+"-claims.key", "--add", "--print-id")
	return strings.TrimSpace(id)
}

// ChainClaimAsStranger chains a claim into a scope signed by a key this repo's trust config knows
// nothing about — a peer's claim arriving by mirror, or an outsider naming a public scope id.
//
// A scope id is public and the substrate restricts nobody from chaining under it, so this state is
// reachable in any federation. It exists to check that an outsider is reported and excluded rather
// than able to affect what this repo can do.
func (r *Repo) ChainClaimAsStranger(t *testing.T, subject, scope, prev, step string) string {
	t.Helper()
	key := filepath.Join("keys", "stranger-"+step)
	runNekton(t, r, "keygen", key)
	return strings.TrimSpace(runNekton(t, r, "annotate", subject,
		"--template", "working-on",
		"--set", "step="+step,
		"--set", "by-session=outsider",
		"--scope", scope, "--prev", prev,
		"--sign", key+".key", "--add", "--print-id"))
}
